services:
  # --- Object Storage Layer (Data Lake) ---
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"

  # --- Relational Database Layer (Data Warehouse) ---
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: caelan
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: nyc_warehouse
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # --- Distributed Compute Engine (Spark Master) ---
  spark-master:
    image: public.ecr.aws/bitnami/spark:3.5.0
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_WEBUI_PORT=8081
    volumes:
      - ./spark/apps:/opt/bitnami/spark/apps
    ports:
      - "8081:8081"
      - "7077:7077"

  # --- Distributed Compute Engine (Spark Worker) ---
  spark-worker:
    image: public.ecr.aws/bitnami/spark:3.5.0
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
    volumes:
      - ./spark/apps:/opt/bitnami/spark/apps

  # --- Workflow Orchestration Layer (Airflow Webserver) ---
  airflow-webserver:
    build: .
    container_name: airflow-webserver
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://caelan:password123@postgres/nyc_warehouse
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=caelan_aristokrat_123
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      # Enables Docker-out-of-Docker (DooD) for Spark job triggering
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db init &&
      airflow users create --username admin --firstname Caelan --lastname Zhou --role Admin --email admin@example.com --password admin &&
      airflow webserver"

  # --- Workflow Orchestration Layer (Airflow Scheduler) ---
  airflow-scheduler:
    build: .
    container_name: airflow-scheduler
    depends_on:
      - postgres
    environment:
      - EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://caelan:password123@postgres/nyc_warehouse
      - AIRFLOW__WEBSERVER__SECRET_KEY=caelan_aristokrat_123
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      # Docker socket binding for remote task execution
      - /var/run/docker.sock:/var/run/docker.sock
    command: scheduler
